"""PDF report of an approved evaluation (CLAUDE.md section 15)."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from uuid import UUID

DOWNLOAD_NAME = "informe-autoevaluacion-inicial.pdf"


@dataclass(frozen=True, slots=True)
class Report:
    id: UUID
    evaluation_id: UUID
    company_id: UUID
    analysis_run_id: UUID
    version: int
    storage_path: str
    size_bytes: int
    sha256: str
    generated_at: datetime


class ReportState(StrEnum):
    NONE = "NONE"
    PENDING = "PENDING"
    READY = "READY"
    FAILED = "FAILED"


def report_path(company_id: UUID, evaluation_id: UUID, report_id: UUID) -> str:
    """Generated by the system; the internal path never reaches the browser."""
    return f"companies/{company_id}/evaluations/{evaluation_id}/reports/{report_id}.pdf"
