"""Generate local, git-ignored environment files from the running Supabase local stack.

Writes:
  .env                 -> backend + docker compose (secrets stay out of the browser)
  apps/web/.env.local  -> Next.js (only public values + server-side API URL)

Development user passwords are random per machine and preserved across runs.
Refuses to run when APP_ENV is pilot or production.
"""

from __future__ import annotations

import os
import secrets
import string
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECT_ID = "pagina_web_iso27001"
SEED_ROLES = ("ADMIN", "REVIEWER", "SME", "SME_B", "MENTOR")
SEED_EMAILS = {
    "ADMIN": "admin@auditor.local",
    "REVIEWER": "revisor@auditor.local",
    "SME": "pyme.a@auditor.local",
    "SME_B": "pyme.b@auditor.local",
    "MENTOR": "mentor@auditor.local",
}


def read_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.lstrip().startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"')
    return values


def supabase_status() -> dict[str, str]:
    command = "pnpm exec supabase status -o env"
    result = subprocess.run(  # noqa: S602 - fixed command, no user input
        command, shell=True, cwd=ROOT, capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        sys.exit("Supabase local is not running. Run: make supabase-start")
    values: dict[str, str] = {}
    for line in result.stdout.splitlines():
        if "=" in line:
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip().strip('"')
    return values


def strong_password() -> str:
    alphabet = string.ascii_letters + string.digits
    while True:
        candidate = "".join(secrets.choice(alphabet) for _ in range(24))
        if (
            any(c.islower() for c in candidate)
            and any(c.isupper() for c in candidate)
            and any(c.isdigit() for c in candidate)
        ):
            return candidate


def write_env(path: Path, header: str, values: dict[str, str]) -> None:
    lines = [f"# {header}", "# Generated by scripts/dev_env.py - DO NOT COMMIT", ""]
    lines += [f"{key}={value}" for key, value in values.items()]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    if os.environ.get("APP_ENV") in {"pilot", "production"}:
        sys.exit("dev_env.py must never run in pilot or production.")
    status = supabase_status()
    previous = read_env(ROOT / ".env")
    db_internal = f"supabase_db_{PROJECT_ID}:5432"
    db_password = status["DB_URL"].split("://", 1)[1].split("@", 1)[0].split(":", 1)[1]
    api_url = status["API_URL"]

    backend = {
        "APP_ENV": "local",
        "DATABASE_URL": f"postgresql+psycopg://postgres:{db_password}@{db_internal}/postgres",
        "TEST_DATABASE_URL": f"postgresql+psycopg://postgres:{db_password}@{db_internal}/auditor_test",
        "SUPABASE_INTERNAL_URL": f"http://supabase_kong_{PROJECT_ID}:8000",
        "SUPABASE_PUBLIC_URL": api_url,
        "SUPABASE_JWT_ISSUER": f"{api_url}/auth/v1",
        "SUPABASE_JWT_AUDIENCE": "authenticated",
        "SUPABASE_SERVICE_ROLE_KEY": status["SECRET_KEY"],
        "ALLOWED_ORIGINS": "http://localhost:3000",
        "LLM_PROVIDER": previous.get("LLM_PROVIDER", "fake"),
        "LLM_API_KEY": previous.get("LLM_API_KEY", ""),
        "LLM_MODEL": previous.get("LLM_MODEL", "openai/gpt-oss-120b"),
    }
    for role in SEED_ROLES:
        backend[f"SEED_{role}_EMAIL"] = previous.get(f"SEED_{role}_EMAIL", SEED_EMAILS[role])
        backend[f"SEED_{role}_PASSWORD"] = previous.get(f"SEED_{role}_PASSWORD") or strong_password()
    write_env(ROOT / ".env", "Local backend environment", backend)

    web = {
        "NEXT_PUBLIC_API_URL": "http://localhost:8000",
        "NEXT_PUBLIC_SUPABASE_URL": api_url,
        "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY": status["PUBLISHABLE_KEY"],
    }
    write_env(ROOT / "apps" / "web" / ".env.local", "Local web environment", web)
    print("Wrote .env and apps/web/.env.local")


if __name__ == "__main__":
    main()
