"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-07

Tables, constraints and indexes are generated from the ORM models. The hand-written part at the
end adds Supabase roles (if missing), RLS deny-by-default, revoked grants and integrity triggers.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("outcome", sa.String(length=10), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=20), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("resource_type", sa.String(length=40), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.CheckConstraint(
            "action IN ('LOGIN', 'LOGOUT', 'ACCESS_DENIED', 'COMPANY_CREATED', 'COMPANY_UPDATED', 'USER_CREATED', 'USER_UPDATED', 'REVIEWER_ASSIGNED', 'EVALUATION_CREATED', 'CONSENT_GIVEN', 'DOCUMENT_UPLOADED', 'DOCUMENT_REJECTED', 'DOCUMENT_DELETED', 'PROCESSING_STARTED', 'PROCESSING_FINISHED', 'PROCESSING_FAILED', 'PROCESSING_RETRIED', 'FINDINGS_GENERATED', 'FINDING_REVIEWED', 'EVALUATION_APPROVED', 'EVALUATION_REJECTED', 'REPORT_GENERATED', 'REPORT_DOWNLOADED', 'CHECKLIST_VERSION_CREATED', 'CHECKLIST_VERSION_PUBLISHED', 'FEEDBACK_SUBMITTED', 'RETENTION_PURGED', 'QUOTA_EXCEEDED')",
            name=op.f("ck_audit_logs_action_valid"),
        ),
        sa.CheckConstraint(
            "outcome IN ('SUCCESS', 'DENIED', 'FAILURE')", name=op.f("ck_audit_logs_outcome_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_company_id", "audit_logs", ["company_id"], unique=False)
    op.create_index("ix_audit_logs_occurred_at", "audit_logs", ["occurred_at"], unique=False)
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tax_id", sa.String(length=40), nullable=True),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index("ix_companies_name_lower", "companies", [sa.text("lower(name)")], unique=False)
    op.create_index(
        "uq_companies_tax_id",
        "companies",
        ["tax_id"],
        unique=True,
        postgresql_where=sa.text("tax_id IS NOT NULL"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('ADMIN', 'REVIEWER', 'SME', 'MENTOR')", name=op.f("ck_users_role_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index("uq_users_email_lower", "users", [sa.text("lower(email)")], unique=True)
    op.create_table(
        "checklist_versions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED')", name=op.f("ck_checklist_versions_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_checklist_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_checklist_versions_version")),
    )
    op.create_table(
        "company_users",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_users_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_company_users_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("company_id", "user_id", name=op.f("pk_company_users")),
        sa.UniqueConstraint("user_id", name=op.f("uq_company_users_user_id")),
    )
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_run_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.String(length=60), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'RECEIVED', 'EXTRACTING', 'ANALYZING', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'FAILED')",
            name=op.f("ck_evaluations_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_evaluations_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_evaluations_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_evaluations_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_evaluations_reviewer_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluations")),
    )
    op.create_index(op.f("ix_evaluations_company_id"), "evaluations", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_evaluations_reviewer_id"), "evaluations", ["reviewer_id"], unique=False
    )
    op.create_index(op.f("ix_evaluations_status"), "evaluations", ["status"], unique=False)
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("checklist_version_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checklist_version_id"],
            ["checklist_versions.id"],
            name=op.f("fk_analysis_runs_checklist_version_id_checklist_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_analysis_runs_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
        sa.UniqueConstraint(
            "evaluation_id", "run_number", name=op.f("uq_analysis_runs_evaluation_id")
        ),
    )
    op.create_index(
        op.f("ix_analysis_runs_evaluation_id"), "analysis_runs", ["evaluation_id"], unique=False
    )
    op.create_table(
        "checklist_items",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evaluation_question", sa.Text(), nullable=False),
        sa.Column("expected_evidence", sa.Text(), nullable=False),
        sa.Column("iso_reference", sa.String(length=80), nullable=True),
        sa.Column("cis_reference", sa.String(length=80), nullable=True),
        sa.Column("nist_reference", sa.String(length=80), nullable=True),
        sa.Column("reference_status", sa.String(length=10), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.String(length=80)), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("effort", sa.String(length=10), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint(
            "effort IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f("ck_checklist_items_effort_valid")
        ),
        sa.CheckConstraint(
            "priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_checklist_items_priority_valid"),
        ),
        sa.CheckConstraint(
            "reference_status IN ('draft', 'confirmed')",
            name=op.f("ck_checklist_items_reference_status_valid"),
        ),
        sa.CheckConstraint(
            "risk_level IN ('LOW', 'MEDIUM', 'HIGH')",
            name=op.f("ck_checklist_items_risk_level_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["checklist_versions.id"],
            name=op.f("fk_checklist_items_version_id_checklist_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_items")),
        sa.UniqueConstraint("version_id", "code", name=op.f("uq_checklist_items_version_id")),
    )
    op.create_index(
        op.f("ix_checklist_items_version_id"), "checklist_items", ["version_id"], unique=False
    )
    op.create_table(
        "consents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("text_version", sa.String(length=20), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_consents_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_consents_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
        sa.UniqueConstraint(
            "evaluation_id", "user_id", "text_version", name=op.f("uq_consents_evaluation_id")
        ),
    )
    op.create_index(op.f("ix_consents_evaluation_id"), "consents", ["evaluation_id"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("usefulness", sa.SmallInteger(), nullable=False),
        sa.Column("ease_of_use", sa.SmallInteger(), nullable=False),
        sa.Column("trust_in_results", sa.SmallInteger(), nullable=False),
        sa.Column("actionable_recommendations", sa.Boolean(), nullable=False),
        sa.Column("manual_time_hours", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("system_time_hours", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("willingness_to_use", sa.SmallInteger(), nullable=False),
        sa.Column("willingness_to_pay", sa.String(length=10), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "willingness_to_pay IN ('YES', 'MAYBE', 'NO')",
            name=op.f("ck_feedback_willingness_to_pay_valid"),
        ),
        sa.CheckConstraint(
            "ease_of_use BETWEEN 1 AND 5", name=op.f("ck_feedback_ease_of_use_scale")
        ),
        sa.CheckConstraint(
            "manual_time_hours >= 0", name=op.f("ck_feedback_manual_time_non_negative")
        ),
        sa.CheckConstraint(
            "system_time_hours >= 0", name=op.f("ck_feedback_system_time_non_negative")
        ),
        sa.CheckConstraint(
            "trust_in_results BETWEEN 1 AND 5", name=op.f("ck_feedback_trust_in_results_scale")
        ),
        sa.CheckConstraint("usefulness BETWEEN 1 AND 5", name=op.f("ck_feedback_usefulness_scale")),
        sa.CheckConstraint(
            "willingness_to_use BETWEEN 1 AND 5", name=op.f("ck_feedback_willingness_to_use_scale")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_feedback_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_feedback_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_feedback_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        sa.UniqueConstraint("evaluation_id", name=op.f("uq_feedback_evaluation_id")),
    )
    op.create_index(op.f("ix_feedback_company_id"), "feedback", ["company_id"], unique=False)
    op.create_table(
        "ai_findings",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("checklist_item_id", sa.Uuid(), nullable=False),
        sa.Column("criterion_code", sa.String(length=10), nullable=False),
        sa.Column("outcome", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("gap", sa.Text(), server_default="", nullable=False),
        sa.Column("recommendation", sa.Text(), server_default="", nullable=False),
        sa.Column("preliminary_priority", sa.String(length=10), nullable=True),
        sa.Column("estimated_effort", sa.String(length=10), nullable=True),
        sa.Column("risk_level", sa.String(length=10), nullable=True),
        sa.Column("requires_human_review", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("has_unverified_citations", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("llm_called", sa.Boolean(), nullable=False),
        sa.Column("error_summary", sa.String(length=300), nullable=True),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estimated_effort IN ('LOW', 'MEDIUM', 'HIGH')",
            name=op.f("ck_ai_findings_effort_valid"),
        ),
        sa.CheckConstraint("outcome IN ('OK', 'ERROR')", name=op.f("ck_ai_findings_outcome_valid")),
        sa.CheckConstraint(
            "preliminary_priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_ai_findings_priority_valid"),
        ),
        sa.CheckConstraint(
            "risk_level IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f("ck_ai_findings_risk_level_valid")
        ),
        sa.CheckConstraint(
            "status IN ('FOUND', 'PARTIAL', 'NO_DOCUMENTARY_EVIDENCE')",
            name=op.f("ck_ai_findings_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_ai_findings_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["checklist_item_id"],
            ["checklist_items.id"],
            name=op.f("fk_ai_findings_checklist_item_id_checklist_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_ai_findings_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_findings")),
        sa.UniqueConstraint(
            "analysis_run_id", "checklist_item_id", name=op.f("uq_ai_findings_analysis_run_id")
        ),
    )
    op.create_index(
        op.f("ix_ai_findings_analysis_run_id"), "ai_findings", ["analysis_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_findings_evaluation_id"), "ai_findings", ["evaluation_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("original_name", sa.String(length=200), nullable=False),
        sa.Column("storage_path", sa.String(length=300), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("has_text", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('STORED', 'EXTRACTED', 'PURGED')", name=op.f("ck_documents_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_documents_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_documents_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_documents_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        op.f("ix_documents_analysis_run_id"), "documents", ["analysis_run_id"], unique=False
    )
    op.create_index(op.f("ix_documents_company_id"), "documents", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_documents_evaluation_id"), "documents", ["evaluation_id"], unique=False
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("criterion_code", sa.String(length=10), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("error_summary", sa.String(length=300), nullable=True),
        sa.Column("structured_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('SUCCESS', 'INVALID_OUTPUT', 'RATE_LIMITED', 'ERROR')",
            name=op.f("ck_llm_calls_outcome_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_llm_calls_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_llm_calls_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_index(
        op.f("ix_llm_calls_analysis_run_id"), "llm_calls", ["analysis_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_calls_evaluation_id"), "llm_calls", ["evaluation_id"], unique=False
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('EXTRACTION', 'ANALYSIS', 'REPORT')",
            name=op.f("ck_processing_jobs_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')",
            name=op.f("ck_processing_jobs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_processing_jobs_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_processing_jobs_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_processing_jobs_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
    )
    op.create_index(
        op.f("ix_processing_jobs_evaluation_id"), "processing_jobs", ["evaluation_id"], unique=False
    )
    op.create_index("ix_processing_jobs_status", "processing_jobs", ["status"], unique=False)
    op.create_index(
        "uq_processing_jobs_active_step",
        "processing_jobs",
        ["evaluation_id", "analysis_run_id", "kind"],
        unique=True,
        postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=300), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_reports_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_reports_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_reports_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["users.id"],
            name=op.f("fk_reports_generated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("evaluation_id", "version", name=op.f("uq_reports_evaluation_id")),
    )
    op.create_index(op.f("ix_reports_company_id"), "reports", ["company_id"], unique=False)
    op.create_index(op.f("ix_reports_evaluation_id"), "reports", ["evaluation_id"], unique=False)
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('spanish'::regconfig, content)", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_document_chunks_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_document_chunks_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name=op.f("uq_document_chunks_document_id")
        ),
    )
    op.create_index(
        op.f("ix_document_chunks_analysis_run_id"),
        "document_chunks",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_evaluation_id"), "document_chunks", ["evaluation_id"], unique=False
    )
    op.create_index(
        "ix_document_chunks_search_vector",
        "document_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "final_findings",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ai_finding_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("checklist_item_id", sa.Uuid(), nullable=False),
        sa.Column("criterion_code", sa.String(length=10), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("gap", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("effort", sa.String(length=10), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("reviewer_comment", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effort IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f("ck_final_findings_effort_valid")
        ),
        sa.CheckConstraint(
            "priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_final_findings_priority_valid"),
        ),
        sa.CheckConstraint(
            "review_status IN ('PENDING_REVIEW', 'APPROVED', 'EDITED_APPROVED', 'DISCARDED')",
            name=op.f("ck_final_findings_review_status_valid"),
        ),
        sa.CheckConstraint(
            "risk_level IN ('LOW', 'MEDIUM', 'HIGH')",
            name=op.f("ck_final_findings_risk_level_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('FOUND', 'PARTIAL', 'NO_DOCUMENTARY_EVIDENCE')",
            name=op.f("ck_final_findings_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_finding_id"],
            ["ai_findings.id"],
            name=op.f("fk_final_findings_ai_finding_id_ai_findings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_final_findings_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["checklist_item_id"],
            ["checklist_items.id"],
            name=op.f("fk_final_findings_checklist_item_id_checklist_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_final_findings_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_final_findings_reviewed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_final_findings")),
        sa.UniqueConstraint("ai_finding_id", name=op.f("uq_final_findings_ai_finding_id")),
    )
    op.create_index(
        op.f("ix_final_findings_analysis_run_id"),
        "final_findings",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_final_findings_evaluation_id"), "final_findings", ["evaluation_id"], unique=False
    )
    op.create_table(
        "human_reviews",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ai_finding_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("previous_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('APPROVE', 'EDIT', 'DISCARD')", name=op.f("ck_human_reviews_action_valid")
        ),
        sa.ForeignKeyConstraint(
            ["ai_finding_id"],
            ["ai_findings.id"],
            name=op.f("fk_human_reviews_ai_finding_id_ai_findings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_human_reviews_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_human_reviews_reviewer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_reviews")),
    )
    op.create_index(
        op.f("ix_human_reviews_ai_finding_id"), "human_reviews", ["ai_finding_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_reviews_evaluation_id"), "human_reviews", ["evaluation_id"], unique=False
    )
    # ### end Alembic commands ###
    _create_security_and_integrity()


def downgrade() -> None:
    _drop_security_and_integrity()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_human_reviews_evaluation_id"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_ai_finding_id"), table_name="human_reviews")
    op.drop_table("human_reviews")
    op.drop_index(op.f("ix_final_findings_evaluation_id"), table_name="final_findings")
    op.drop_index(op.f("ix_final_findings_analysis_run_id"), table_name="final_findings")
    op.drop_table("final_findings")
    op.drop_index(
        "ix_document_chunks_search_vector", table_name="document_chunks", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_document_chunks_evaluation_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_analysis_run_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_reports_evaluation_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_company_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(
        "uq_processing_jobs_active_step",
        table_name="processing_jobs",
        postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"),
    )
    op.drop_index("ix_processing_jobs_status", table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_evaluation_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_llm_calls_evaluation_id"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_analysis_run_id"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_documents_evaluation_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_company_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_analysis_run_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_ai_findings_evaluation_id"), table_name="ai_findings")
    op.drop_index(op.f("ix_ai_findings_analysis_run_id"), table_name="ai_findings")
    op.drop_table("ai_findings")
    op.drop_index(op.f("ix_feedback_company_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_consents_evaluation_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(op.f("ix_checklist_items_version_id"), table_name="checklist_items")
    op.drop_table("checklist_items")
    op.drop_index(op.f("ix_analysis_runs_evaluation_id"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_index(op.f("ix_evaluations_status"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_reviewer_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_company_id"), table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_table("company_users")
    op.drop_table("checklist_versions")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_index(
        "uq_companies_tax_id",
        table_name="companies",
        postgresql_where=sa.text("tax_id IS NOT NULL"),
    )
    op.drop_index("ix_companies_name_lower", table_name="companies")
    op.drop_table("companies")
    op.drop_index("ix_audit_logs_occurred_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_company_id", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###


TABLES = (
    "users",
    "companies",
    "company_users",
    "consents",
    "evaluations",
    "analysis_runs",
    "documents",
    "document_chunks",
    "checklist_versions",
    "checklist_items",
    "ai_findings",
    "human_reviews",
    "final_findings",
    "reports",
    "feedback",
    "processing_jobs",
    "llm_calls",
    "audit_logs",
)

APPEND_ONLY_TABLES = ("audit_logs", "ai_findings", "human_reviews", "llm_calls")


def _create_security_and_integrity() -> None:
    # Supabase already provides these roles; plain PostgreSQL (e.g. other environments) does not.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                CREATE ROLE anon NOLOGIN;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                CREATE ROLE authenticated NOLOGIN;
            END IF;
        END
        $$;
        """
    )
    # Deny by default: RLS enabled without policies and no grants for client-facing roles.
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"REVOKE ALL ON TABLE {table} FROM anon, authenticated")

    op.execute(
        """
        CREATE FUNCTION auditor_reject_modification() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = 'restrict_violation';
        END
        $$;
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION auditor_reject_modification()"
        )

    op.execute(
        """
        CREATE FUNCTION auditor_protect_published_version() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status = 'PUBLISHED' THEN
                RAISE EXCEPTION 'published checklist versions are immutable'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN COALESCE(NEW, OLD);
        END
        $$;
        """
    )
    op.execute(
        "CREATE TRIGGER checklist_versions_immutable BEFORE UPDATE OR DELETE ON checklist_versions "
        "FOR EACH ROW EXECUTE FUNCTION auditor_protect_published_version()"
    )
    op.execute(
        """
        CREATE FUNCTION auditor_protect_published_items() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP <> 'INSERT' AND EXISTS (
                SELECT 1 FROM checklist_versions v
                WHERE v.id = OLD.version_id AND v.status = 'PUBLISHED'
            ) THEN
                RAISE EXCEPTION 'items of a published checklist version are immutable'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF TG_OP <> 'DELETE' AND EXISTS (
                SELECT 1 FROM checklist_versions v
                WHERE v.id = NEW.version_id AND v.status = 'PUBLISHED'
            ) THEN
                RAISE EXCEPTION 'items of a published checklist version are immutable'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN COALESCE(NEW, OLD);
        END
        $$;
        """
    )
    op.execute(
        "CREATE TRIGGER checklist_items_immutable BEFORE INSERT OR UPDATE OR DELETE "
        "ON checklist_items FOR EACH ROW EXECUTE FUNCTION auditor_protect_published_items()"
    )


def _drop_security_and_integrity() -> None:
    op.execute("DROP TRIGGER IF EXISTS checklist_items_immutable ON checklist_items")
    op.execute("DROP TRIGGER IF EXISTS checklist_versions_immutable ON checklist_versions")
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS auditor_protect_published_items()")
    op.execute("DROP FUNCTION IF EXISTS auditor_protect_published_version()")
    op.execute("DROP FUNCTION IF EXISTS auditor_reject_modification()")
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
