"""final findings discarded without classification

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07 22:53:20.598646
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("final_findings", "status", existing_type=sa.VARCHAR(length=30), nullable=True)
    op.alter_column(
        "final_findings", "priority", existing_type=sa.VARCHAR(length=10), nullable=True
    )
    op.alter_column("final_findings", "effort", existing_type=sa.VARCHAR(length=10), nullable=True)
    op.alter_column(
        "final_findings", "risk_level", existing_type=sa.VARCHAR(length=10), nullable=True
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_final_findings_classified_unless_discarded"),
        "final_findings",
        "review_status = 'DISCARDED' OR (status IS NOT NULL AND priority IS NOT NULL "
        "AND effort IS NOT NULL AND risk_level IS NOT NULL)",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("ck_final_findings_classified_unless_discarded"), "final_findings", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "final_findings", "risk_level", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.alter_column("final_findings", "effort", existing_type=sa.VARCHAR(length=10), nullable=False)
    op.alter_column(
        "final_findings", "priority", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.alter_column("final_findings", "status", existing_type=sa.VARCHAR(length=30), nullable=False)
    # ### end Alembic commands ###
