"""Object storage adapters.

Buckets are private; clients only ever receive short-lived signed URLs.
"""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import time
from pathlib import Path
from typing import Any
from urllib.parse import quote, urlencode

import httpx

from auditor.shared.domain.errors import ProcessingError, ResourceNotFoundError

_SAFE_SEGMENT = frozenset("abcdefghijklmnopqrstuvwxyz0123456789-_.")


def _check_path(path: str) -> str:
    """Storage paths are generated by the system; reject anything unexpected defensively."""
    parts = path.split("/")
    if not parts or any(not part or part in {".", ".."} for part in parts):
        raise ValueError(f"invalid storage path: {path!r}")
    if any(set(part.lower()) - _SAFE_SEGMENT for part in parts):
        raise ValueError(f"invalid storage path: {path!r}")
    return path


class SupabaseStorage:
    def __init__(
        self, base_url: str, public_url: str, service_role_key: str, http: httpx.AsyncClient
    ) -> None:
        self._base = base_url.rstrip("/") + "/storage/v1"
        self._public = public_url.rstrip("/") + "/storage/v1"
        self._headers = {
            "apikey": service_role_key,
            "authorization": f"Bearer {service_role_key}",
        }
        self._http = http

    async def _request(self, method: str, url: str, **kwargs: Any) -> httpx.Response:
        headers = {**self._headers, **kwargs.pop("headers", {})}
        try:
            return await self._http.request(method, url, headers=headers, timeout=60.0, **kwargs)
        except httpx.HTTPError as exc:
            raise ProcessingError(detail=f"storage request failed: {type(exc).__name__}") from exc

    async def upload(self, bucket: str, path: str, data: bytes, content_type: str) -> None:
        response = await self._request(
            "POST",
            f"{self._base}/object/{bucket}/{_check_path(path)}",
            content=data,
            headers={"content-type": content_type, "x-upsert": "false"},
        )
        if not response.is_success:
            raise ProcessingError(detail=f"storage upload failed: {response.status_code}")

    async def download(self, bucket: str, path: str) -> bytes:
        response = await self._request("GET", f"{self._base}/object/{bucket}/{_check_path(path)}")
        if response.status_code in {400, 404}:
            raise ResourceNotFoundError(detail="storage object not found")
        if not response.is_success:
            raise ProcessingError(detail=f"storage download failed: {response.status_code}")
        return response.content

    async def delete(self, bucket: str, path: str) -> None:
        response = await self._request(
            "DELETE", f"{self._base}/object/{bucket}", json={"prefixes": [_check_path(path)]}
        )
        if not response.is_success:
            raise ProcessingError(detail=f"storage delete failed: {response.status_code}")

    async def create_signed_url(
        self, bucket: str, path: str, ttl_seconds: int, download_name: str | None
    ) -> str:
        response = await self._request(
            "POST",
            f"{self._base}/object/sign/{bucket}/{_check_path(path)}",
            json={"expiresIn": ttl_seconds},
        )
        if not response.is_success:
            raise ProcessingError(detail=f"storage signing failed: {response.status_code}")
        signed = str(response.json()["signedURL"])
        if download_name is None:
            return f"{self._public}{signed}"
        separator = "&" if "?" in signed else "?"
        return f"{self._public}{signed}{separator}{urlencode({'download': download_name})}"


class LocalDiskStorage:
    """Test-only adapter (APP_ENV=test). Signed URLs are HMAC tokens that tests can verify."""

    def __init__(self, root: Path, signing_key: bytes, public_url: str) -> None:
        self._root = root
        self._key = signing_key
        self._public = public_url.rstrip("/")

    def _file(self, bucket: str, path: str) -> Path:
        return self._root / bucket / _check_path(path)

    async def upload(self, bucket: str, path: str, data: bytes, content_type: str) -> None:
        target = self._file(bucket, path)
        if target.exists():
            raise ProcessingError(detail="object already exists")
        await asyncio.to_thread(target.parent.mkdir, parents=True, exist_ok=True)
        await asyncio.to_thread(target.write_bytes, data)

    async def download(self, bucket: str, path: str) -> bytes:
        target = self._file(bucket, path)
        if not target.exists():
            raise ResourceNotFoundError(detail="storage object not found")
        return await asyncio.to_thread(target.read_bytes)

    async def delete(self, bucket: str, path: str) -> None:
        await asyncio.to_thread(self._file(bucket, path).unlink, missing_ok=True)

    async def create_signed_url(
        self, bucket: str, path: str, ttl_seconds: int, download_name: str | None
    ) -> str:
        expires = int(time.time()) + ttl_seconds
        message = f"{bucket}/{_check_path(path)}:{expires}".encode()
        signature = hmac.new(self._key, message, hashlib.sha256).hexdigest()
        params: dict[str, str | int] = {"expires": expires, "signature": signature}
        if download_name is not None:
            params["download"] = download_name
        query = urlencode(params)
        return f"{self._public}/local-storage/{bucket}/{quote(path)}?{query}"

    def exists(self, bucket: str, path: str) -> bool:
        return self._file(bucket, path).exists()
